export const SEARCH_RESULT_START = "SEARCH_RESULT_START";
export const SEARCH_RESULT_SUCCESS = "SEARCH_RESULT_SUCCESS";
export const SEARCH_RESULT_ERROR = "SEARCH_RESULT_ERROR";

export const ADD_FAV_PACKAGE = "ADD_FAV_PACKAGE";
export const DEL_FAV_PACKAGE = "DEL_FAV_PACKAGE";
